FROM alpine

RUN apt-get update && apt-get install -y \
  bzr \
  cvs \
  git \
  mercurial \
  subversion

ENV ADMIN_USER="mark"
RUN echo $ADMIN_USER > ./mark
RUN unset ADMIN_USER
ADD https://www.test.com/index.html /tmp/
ADD . /tmp/
ADD script.sh /tmp/
RUN pip install --requirement /tmp/requirements.txt