swagger: "2.0"
info:
  description: "SDS is a tool to detect and implement security best practices over docker containers"
  version: "1.0.0"
  title: "SDS Swagger API specification"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/sds"
schemes:
- "http"
paths:
  /health:
    get:
      summary: "Check application status"
      description: "Returns application status"
      operationId: "checkApplicationStatus"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
  /containers:
    get:
      summary: "List containers running on host"
      description: "Returns container findings"
      operationId: "get containers"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Container"
  /containers/{id}/check:
    get:
      summary: "Check container by ID"
      description: "Returns container findings"
      operationId: "checkContainerById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id of docker container"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
  /containers/{id}/fix:
    get:
      summary: "Fix container by ID"
      description: "Returns container findings and create a Dockerfile with the fixes"
      operationId: "fixContainerById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id of docker container"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
  /images/dockerfile/check:
    post:
      summary: "Analyse Dockerfile"
      description: ""
      operationId: "analyseDockerfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dockerfile"
        required: true
        schema:
          $ref: "#/definitions/Dockerfile"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
  /images/dockerfile/fix:
    post:
      summary: "Analyse Dockerfile"
      description: ""
      operationId: "analyseDockerfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dockerfile"
        required: true
        schema:
          $ref: "#/definitions/Dockerfile"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
definitions:
  Container:
    properties:
      id:
        type: "string"
  Dockerfile:
    properties:
      dockerFile:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"